### ISSUE TITLE
Implement `*_{add,sub}_{signed,unsigned}` methods.

### ISSUE THREAD

**Issue by nlordell** [nlordell/ethnum-rs#24]
They were stabilized in [Rust 1.66](https://blog.rust-lang.org/2022/12/15/Rust-1.66.0.html).

**Comment by NCGThompson** [comment]
Is there any reason (e.g. licensing incompatibility) to not just copy + paste the integer implementation macros from the core library? That seems to be the best option considering the goal is a common interface with the native integers. All of theses functions are derived from intrinsics already implemented.

**Comment by nlordell** [comment]
> Is there any reason (e.g. licensing incompatibility) to not just copy + paste the integer implementation macros from the core library?

Would you copy the whole integer implementation macros? That's a nice idea and will experiment and see if it "just works" without modifications.

**Comment by NCGThompson** [comment]
see if it "just works" without modifications.

It won't completely. At least not while strictly using stable features. I don't think we will lose much my deleting the unstable stuff though. I'll get to it.
