### ISSUE TITLE
LTO doesn't appear to affect llvm intrinsics.

### ISSUE THREAD

**Issue by NCGThompson** [nlordell/ethnum-rs#33]
The readme suggests that linker-plugin-lto is required for `llvm` intrinsics to be faster than `native` intrinsics.

> Additionally, Rust usually optimizes when compiling and linking Rust code (and not externally linked code), this means that these intrinsics cannot be inlined adding an extra function call overhead in some cases which make it perform worse than the native Rust implementation despite having more optimized assembly. Luckily, Rust currently has support for linker plugin LTO to enable optimizations during the link step, enabling optimizations with Clang-compiled LLVM IR.

However, every way I tried to build it, the llvm intrinsics are never inlined and seem opaque to the optimizer. The optimizer doesn't even realize they don't have side effects, inhibiting dead code elimination.

The instructions say in bold **"Note that the clang version must match the rustc LLVM version."** I am using the same major version, 17, but not the same minor version. I am not sure if that has anything to do with it, because the LTO works well between rust crates when llvm-intrinsics is disabled.

<details>
<summary>
version information
</summary>

```
rustc 1.73.0 (cc66ad468 2023-10-03)
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: x86_64-unknown-linux-gnu
release: 1.73.0
LLVM version: 17.0.2
```

```
Debian clang version 17.0.4 (++20231031083056+309d55140c46-1~exp1~20231031083156.63)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
</details>

**Comment by NCGThompson** [comment]
According to the rustc documentation, `-C lto` should be irrelevant when `-C linker-plugin-lto` is set. However, when `C lto` is "off" or "false", no LTO happens what so ever. Therefor, I am probably doing it incorrectly. I will still keep this issue open until I solve it because this could be an opportunity for documentation improvement.

**Comment by NCGThompson** [comment]
I found one thing I was doing wrong: I did not set `export CLANG=clang-17`.  Unfortunately, it still isn't working, and I have yet to see `linker-plugin-lto` make any difference whatsoever. I know the environment variable is being respected because `export CLANG=clang-18` causes the build to fail. (I don't have 18 installed).

To makes sure I wasn't just seeing the assembly output before the LTO took place, I used objdump to view the final linked executable. To make sure the issue wasn't the difference between 17.0.2 and 17.0.4, I switched to rust nightly. However, clang automatically updated to 17.0.5, so it still wasn't an exact match. I couldn't revert clang, but I marked it as hold to give rust nightly time to catch up.

What I will try next:
* Follow the macOS instructions as closely as possible on Debian and see if that works.
* Compile another library with external dependencies and see if I have the same issue.

**Comment by nlordell** [comment]
OK - I think its an issue with the intrinsics build script. I see inlining when I comment out this:

```diff
diff --git a/intrinsics/build/main.rs b/intrinsics/build/main.rs
index bb063cf..6361fec 100644
--- a/intrinsics/build/main.rs
+++ b/intrinsics/build/main.rs
@@ -52,9 +52,9 @@ fn main() -> Result<(), Box<dyn Error>> {
 
     let linker_plugin_lto =
         matches!(env::var("RUSTFLAGS"), Ok(flags) if flags.contains("-Clinker-plugin-lto"));
-    if linker_plugin_lto {
+    //if linker_plugin_lto {
         build.flag("-flto=thin");
-    }
+    //}
 
     build.try_compile("ethnum")?;
     Ok(())

```
